
DB_HOST = '192.168.223.128'
DB_PORT = 27017

MOOD_JOURNAL_DB_NAME = 'mj'
FORMS_COLLECTION_NAME = 'forms'
SAD_REASONS_COLLECTION_NAME = 'sad_reasons'
HAPPY_REASONS_COLLECTION_NAME = 'happy_reasons'


